const GALLERY_DATA = [
  {
    id: 1,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Christmascelebration.png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 2,
    type: "vid",
    thumb: "https://img.youtube.com/vi/ORcTixWcdtA/hqdefault.jpg",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Reel",
    video: "https://youtube.com/shorts/ORcTixWcdtA",
  },
  {
    id: 3,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/laddu3.png",
    alt: "Laddu Activity",
    title: "Laddu Activity",
    tag: "Activity Day",
  },
  {
    id: 4,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Compusdrive.png",
    alt: "Campus Drive",
    title: "Campus Drive",
    tag: "Campus Day",
  },
  {
    id: 5,
    type: "vid",
    thumb: "https://img.youtube.com/vi/SSgrZe2y4WI/hqdefault.jpg",
    alt: "Christmas Activity",
    title: "Christmas Activity",
    tag: "Festival Reel",
    video: "https://youtube.com/shorts/SSgrZe2y4WI",
  },
  {
    id: 6,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/diwali.png",
    alt: "Diwali Celebration",
    title: "Diwali Celebration",
    tag: "Festival Day",
  },
  {
    id: 7,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/maskmaking.png",
    alt: "Mask Activity",
    title: "Mask Activity",
    tag: "Creative Day",
  },
  {
    id: 8,
    type: "vid",
    thumb: "https://img.youtube.com/vi/CbOxm06tYHQ/hqdefault.jpg",
    alt: "Laddu Activity",
    title: "Laddu Activity",
    tag: "Activity Reel",
    video: "https://youtube.com/shorts/CbOxm06tYHQ",
  },
  {
    id: 9,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/trip.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 10,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/PlatinumCelebration.png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
  {
    id: 11,
    type: "vid",
    thumb: "https://img.youtube.com/vi/qWsfsW2WFa8/hqdefault.jpg",
    alt: "Diwali Celebration",
    title: "Diwali Celebration",
    tag: "Festival Reel",
    video: "https://youtube.com/shorts/qWsfsW2WFa8",
  },
  {
    id: 12,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/christmaseve9.png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 13,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/RNR.png",
    alt: "RNR Celebration",
    title: "RNR Celebration",
    tag: "Recognition Day",
  },
  {
    id: 14,
    type: "vid",
    thumb: "https://img.youtube.com/vi/nE6LCBUmafc/hqdefault.jpg",
    alt: "Clay Activity",
    title: "Clay Activity",
    tag: "Activity Reel",
    video: "https://youtube.com/shorts/nE6LCBUmafc",
  },
  {
    id: 15,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/trip39.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 16,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Saturday%20activity.png",
    alt: "Weekend Activity",
    title: "Weekend Activity",
    tag: "Fun Day",
  },
  {
    id: 17,
    type: "vid",
    thumb: "https://img.youtube.com/vi/Nvsk5Qwxu6Q/hqdefault.jpg",
    alt: "RNR Celebration",
    title: "RNR Celebration",
    tag: "Recognition Reel",
    video: "https://youtube.com/shorts/Nvsk5Qwxu6Q",
  },
  {
    id: 18,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Platinum%20Partner%20Celebration.png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
  {
    id: 19,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/clayactivity.png",
    alt: "Clay Activity",
    title: "Clay Activity",
    tag: "Creative Day",
  },
  {
    id: 20,
    type: "vid",
    thumb: "https://img.youtube.com/vi/5J9jwD3SDw4/hqdefault.jpg",
    alt: "Holi",
    title: "Holi Celebration",
    tag: "Festival Reel",
    video: "https://youtube.com/shorts/5J9jwD3SDw4",
  },
  {
    id: 21,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Diwaliceleb44.png",
    alt: "Diwali Celebration",
    title: "Diwali Celebration",
    tag: "Festival Day",
  },
  {
    id: 22,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/turf-sat7.png",
    alt: "Turf Activity",
    title: "Turf Activity",
    tag: "Sports Day",
  },
  {
    id: 23,
    type: "vid",
    thumb: "https://img.youtube.com/vi/gJhS8aZtruw/hqdefault.jpg",
    alt: "Turf Activity V2",
    title: "Turf Activity V2",
    tag: "Sports Reel",
    video: "https://youtube.com/shorts/gJhS8aZtruw",
  },
  {
    id: 24,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/christmas26.png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 25,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Trip%202.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 26,
    type: "vid",
    thumb: "https://img.youtube.com/vi/MzgKhbYV1TE/hqdefault.jpg",
    alt: "Housie Activity (Tambola)",
    title: "Housie Activity (Tambola)",
    tag: "Games Reel",
    video: "https://youtube.com/shorts/MzgKhbYV1TE",
  },
  {
    id: 27,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/rnr57.png",
    alt: "RNR Celebration",
    title: "RNR Celebration",
    tag: "Recognition Day",
  },
  {
    id: 28,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Mask%202.png",
    alt: "Mask Activity",
    title: "Mask Activity",
    tag: "Creative Day",
  },
  {
    id: 29,
    type: "vid",
    thumb: "https://img.youtube.com/vi/10sQa-ze_Bs/hqdefault.jpg",
    alt: "Turf Activity V3",
    title: "Turf Activity V3",
    tag: "Sports Reel",
    video: "https://youtube.com/shorts/10sQa-ze_Bs",
  },
  {
    id: 30,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/compus9.png",
    alt: "Campus Drive",
    title: "Campus Drive",
    tag: "Campus Day",
  },
  {
    id: 31,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/welcome1.png",
    alt: "Welcoming New Gems V1",
    title: "Welcoming New Gems",
    tag: "Welcome Day",
  },
  {
    id: 32,
    type: "vid",
    thumb: "https://img.youtube.com/vi/zWofI7qY7yk/hqdefault.jpg",
    alt: "Mask Activity",
    title: "Mask Activity",
    tag: "Creative Reel",
    video: "https://www.youtube.com/watch?v=zWofI7qY7yk",
  },
  {
    id: 33,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/15.png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 34,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Diwali60.png",
    alt: "Diwali Celebration",
    title: "Diwali Celebration",
    tag: "Festival Day",
  },
  {
    id: 35,
    type: "vid",
    thumb: "https://img.youtube.com/vi/aukvIza8e6w/hqdefault.jpg",
    alt: "Forest Day",
    title: "Forest Day",
    tag: "Activity Reel",
    video: "https://www.youtube.com/shorts/aukvIza8e6w",
  },
  {
    id: 36,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Trip33.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 37,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/laddu%20making8.png",
    alt: "Laddu Activity",
    title: "Laddu Activity",
    tag: "Activity Day",
  },
  {
    id: 38,
    type: "vid",
    thumb: "https://img.youtube.com/vi/V8qzhANGSUY/hqdefault.jpg",
    alt: "Womans Day Celebration",
    title: "Womans Day Celebration",
    tag: "Celebration Reel",
    video: "https://www.youtube.com/shorts/V8qzhANGSUY",
  },
  {
    id: 39,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/platnium18.png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
  {
    id: 40,
    type: "vid",
    thumb: "https://img.youtube.com/vi/rAVIJnZlXP0/hqdefault.jpg",
    alt: "Turf Activity V1",
    title: "Turf Activity V1",
    tag: "Sports Reel",
    video: "https://www.youtube.com/shorts/rAVIJnZlXP0",
  },
  {
    id: 41,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/chrismtas10.png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 42,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/trip6.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 43,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Rnr56.png",
    alt: "RNR Celebration",
    title: "RNR Celebration",
    tag: "Recognition Day",
  },
  {
    id: 44,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Platinum%20%20Celebration.png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
  {
    id: 45,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Trip30.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 46,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/christmas5.png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 47,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Compusdriv1.png",
    alt: "Campus Drive",
    title: "Campus Drive",
    tag: "Campus Day",
  },
  {
    id: 48,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Trip29.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 49,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/mask53.png",
    alt: "Mask Activity",
    title: "Mask Activity",
    tag: "Creative Day",
  },
  {
    id: 50,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/welcomkit.png",
    alt: "Welcoming New Gems V2",
    title: "Welcoming New Gems V2",
    tag: "Welcome Day",
  },
  {
    id: 51,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/trip34.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 52,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/fun63.png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 53,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Compus%20Drive%20.png",
    alt: "Campus Drive",
    title: "Campus Drive",
    tag: "Campus Day",
  },
  {
    id: 54,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/trip31.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 55,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/diwali%20celebration.png",
    alt: "Diwali Celebration",
    title: "Diwali Celebration",
    tag: "Festival Day",
  },
  {
    id: 56,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Saturday%20act.45.png",
    alt: "Weekend Activity",
    title: "Weekend Activity",
    tag: "Fun Day",
  },
  {
    id: 57,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/trip38.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 58,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Platinum%20Partner.png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
  {
    id: 59,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Compus%20drive%2071.png",
    alt: "Campus Drive",
    title: "Campus Drive",
    tag: "Campus Day",
  },
  {
    id: 60,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/trip32.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 61,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/laddumaking49.png",
    alt: "Laddu Activity",
    title: "Laddu Activity",
    tag: "Activity Day",
  },
  {
    id: 62,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/christmas8.png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 63,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/trip36.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 64,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/truf28.png",
    alt: "Turf Activity",
    title: "Turf Activity",
    tag: "Sports Day",
  },
  {
    id: 65,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/deadline.png",
    alt: "Project Handover",
    title: "Project Handover",
    tag: "Work Day",
  },
  {
    id: 66,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/satactivity8.png",
    alt: "Weekend Activity",
    title: "Weekend Activity",
    tag: "Fun Day",
  },
  {
    id: 67,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/welcomeintern40.png",
    alt: "Womans Day Celebration",
    title: "Womans Day Celebration",
    tag: "Celebration Day",
  },
  {
    id: 68,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Compus%20drive%208.png",
    alt: "Campus Drive",
    title: "Campus Drive",
    tag: "Campus Day",
  },
  {
    id: 69,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/platinum.png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
  {
    id: 70,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/Compus%20drive6.png",
    alt: "Campus Drive",
    title: "Campus Drive",
    tag: "Campus Day",
  },
  {
    id: 71,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/RNR5.png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
];
