const GALLERY_DATA = [
  {
    id: 1,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Christmas%20Celebration.png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 2,
    type: "vid",
    thumb: "https://img.youtube.com/vi/ORcTixWcdtA/hqdefault.jpg",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Reel",
    video: "https://youtube.com/shorts/ORcTixWcdtA",
  },
  {
    id: 3,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Laddu%20Activity.png",
    alt: "Laddu Activity",
    title: "Laddu Activity",
    tag: "Activity Day",
  },
  {
    id: 4,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Campus%20Drive.png",
    alt: "Campus Drive",
    title: "Campus Drive",
    tag: "Campus Day",
  },
  {
    id: 5,
    type: "vid",
    thumb: "https://img.youtube.com/vi/SSgrZe2y4WI/hqdefault.jpg",
    alt: "Christmas Activity",
    title: "Christmas Activity",
    tag: "Festival Reel",
    video: "https://youtube.com/shorts/SSgrZe2y4WI",
  },
  {
    id: 6,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Diwali%20Celebration%20(3).png",
    alt: "Diwali Celebration",
    title: "Diwali Celebration",
    tag: "Festival Day",
  },
  {
    id: 7,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Mask%20Activity.png",
    alt: "Mask Activity",
    title: "Mask Activity",
    tag: "Creative Day",
  },
  {
    id: 8,
    type: "vid",
    thumb: "https://img.youtube.com/vi/CbOxm06tYHQ/hqdefault.jpg",
    alt: "Laddu Activity",
    title: "Laddu Activity",
    tag: "Activity Reel",
    video: "https://youtube.com/shorts/CbOxm06tYHQ",
  },
  {
    id: 9,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/OMkareshwar%20Trip.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 10,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Make%20Platanium%20Celebration.png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
  {
    id: 11,
    type: "vid",
    thumb: "https://img.youtube.com/vi/qWsfsW2WFa8/hqdefault.jpg",
    alt: "Diwali Celebration",
    title: "Diwali Celebration",
    tag: "Festival Reel",
    video: "https://youtube.com/shorts/qWsfsW2WFa8",
  },
  {
    id: 12,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/RNR%20Celebration.png",
    alt: "RNR Celebration",
    title: "RNR Celebration",
    tag: "Recognition Day",
  },
  {
    id: 13,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Clay%20Activity.png",
    alt: "Clay Activity",
    title: "Clay Activity",
    tag: "Creative Day",
  },
  {
    id: 14,
    type: "vid",
    thumb: "https://img.youtube.com/vi/nE6LCBUmafc/hqdefault.jpg",
    alt: "Clay Activity",
    title: "Clay Activity",
    tag: "Activity Reel",
    video: "https://youtube.com/shorts/nE6LCBUmafc",
  },
  {
    id: 15,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Omkareshwar%20Trip%20(6).png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 16,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Fun%20Activity.png",
    alt: "Fun Activity",
    title: "Fun Activity",
    tag: "Fun Day",
  },
  {
    id: 17,
    type: "vid",
    thumb: "https://img.youtube.com/vi/Nvsk5Qwxu6Q/hqdefault.jpg",
    alt: "RNR Celebration",
    title: "RNR Celebration",
    tag: "Recognition Reel",
    video: "https://youtube.com/shorts/Nvsk5Qwxu6Q",
  },
  {
    id: 18,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Plantation%20Activity.png",
    alt: "Plantation Activity",
    title: "Plantation Activity",
    tag: "CSR Day",
  },
  {
    id: 19,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Team%20Growwstacks.png",
    alt: "Team GrowwStacks",
    title: "Team GrowwStacks",
    tag: "Spirit Day",
  },
  {
    id: 20,
    type: "vid",
    thumb: "https://img.youtube.com/vi/5J9jwD3SDw4/hqdefault.jpg",
    alt: "Holi Celebration",
    title: "Holi Celebration",
    tag: "Festival Reel",
    video: "https://youtube.com/shorts/5J9jwD3SDw4",
  },
  {
    id: 21,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Turf%20Activity.png",
    alt: "Turf Activity",
    title: "Turf Activity",
    tag: "Sports Day",
  },
  {
    id: 22,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Welcoming%20New%20Gems%20V1.png",
    alt: "Welcoming New Gems",
    title: "Welcoming New Gems",
    tag: "Welcome Day",
  },
  {
    id: 23,
    type: "vid",
    thumb: "https://img.youtube.com/vi/gJhS8aZtruw/hqdefault.jpg",
    alt: "Turf Activity",
    title: "Turf Activity",
    tag: "Sports Reel",
    video: "https://youtube.com/shorts/gJhS8aZtruw",
  },
  {
    id: 24,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/RNR%20Activity%20%20(3).png",
    alt: "RNR Activity",
    title: "RNR Activity",
    tag: "Recognition Day",
  },
  {
    id: 25,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Plantation%20Activity%20(5).png",
    alt: "Plantation Activity",
    title: "Plantation Activity",
    tag: "CSR Day",
  },
  {
    id: 26,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Office.png",
    alt: "GrowwStacks Office",
    title: "GrowwStacks Office",
    tag: "Work Day",
  },
  {
    id: 27,
    type: "vid",
    thumb: "https://img.youtube.com/vi/MzgKhbYV1TE/hqdefault.jpg",
    alt: "Housie Activity (Tambola)",
    title: "Housie Activity (Tambola)",
    tag: "Games Reel",
    video: "https://youtube.com/shorts/MzgKhbYV1TE",
  },
  {
    id: 28,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Mask%20Activity%20(2).png",
    alt: "Mask Activity",
    title: "Mask Activity",
    tag: "Creative Day",
  },
  {
    id: 29,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Campus%20Drive%20(6).png",
    alt: "Campus Drive",
    title: "Campus Drive",
    tag: "Campus Day",
  },
  {
    id: 30,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Diwali%20Celebration%20(5).png",
    alt: "Diwali Celebration",
    title: "Diwali Celebration",
    tag: "Festival Day",
  },
  {
    id: 31,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Make%20Platanium%20Celebration%20(2).png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
  {
    id: 32,
    type: "vid",
    thumb: "https://img.youtube.com/vi/10sQa-ze_Bs/hqdefault.jpg",
    alt: "Turf Activity",
    title: "Turf Activity",
    tag: "Sports Reel",
    video: "https://youtube.com/shorts/10sQa-ze_Bs",
  },
  {
    id: 33,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Omkareshwar%20Trip%20(3).png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 34,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Laddu%20Activity%20(2).png",
    alt: "Laddu Activity",
    title: "Laddu Activity",
    tag: "Activity Day",
  },
  {
    id: 35,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Womans%20Day%20(4).png",
    alt: "Womans Day Celebration",
    title: "Womans Day Celebration",
    tag: "Celebration Day",
  },
  {
    id: 36,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Cricket%20Turf.png",
    alt: "Cricket Turf",
    title: "Cricket Turf",
    tag: "Sports Day",
  },
  {
    id: 37,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Project%20Delevery.png",
    alt: "Project Delivery",
    title: "Project Delivery",
    tag: "Work Day",
  },
  {
    id: 38,
    type: "vid",
    thumb: "https://img.youtube.com/vi/V8qzhANGSUY/hqdefault.jpg",
    alt: "Womans Day Celebration",
    title: "Womans Day Celebration",
    tag: "Celebration Reel",
    video: "https://www.youtube.com/shorts/V8qzhANGSUY",
  },
  {
    id: 39,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Christmas%20Celebration%20(3).png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 40,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Team%20Growwstacks%20(3).png",
    alt: "Team GrowwStacks",
    title: "Team GrowwStacks",
    tag: "Spirit Day",
  },
  {
    id: 41,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Plantation%20Activity%20(2).png",
    alt: "Plantation Activity",
    title: "Plantation Activity",
    tag: "CSR Day",
  },
  {
    id: 42,
    type: "vid",
    thumb: "https://img.youtube.com/vi/rAVIJnZlXP0/hqdefault.jpg",
    alt: "Turf Activity",
    title: "Turf Activity",
    tag: "Sports Reel",
    video: "https://www.youtube.com/shorts/rAVIJnZlXP0",
  },
  {
    id: 44,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Fun%20Activity%20(3).png",
    alt: "Fun Activity",
    title: "Fun Activity",
    tag: "Fun Day",
  },
  {
    id: 45,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Omkareshwar%20Trip%20(4).png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 46,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Clay%20Activity%20(2).png",
    alt: "Clay Activity",
    title: "Clay Activity",
    tag: "Creative Day",
  },
  {
    id: 47,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Campus%20Drive%20(7).png",
    alt: "Campus Drive",
    title: "Campus Drive",
    tag: "Campus Day",
  },
  {
    id: 48,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Cristmas%20Celebration.png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 49,
    type: "vid",
    thumb: "https://img.youtube.com/vi/zWofI7qY7yk/hqdefault.jpg",
    alt: "Mask Activity",
    title: "Mask Activity",
    tag: "Creative Reel",
    video: "https://www.youtube.com/watch?v=zWofI7qY7yk",
  },
  {
    id: 50,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Make%20Platanium%20Celebration%20(3).png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
  {
    id: 51,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Omkareshwar%20Trip%20(5).png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 52,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/RNR%20Activity.png",
    alt: "RNR Activity",
    title: "RNR Activity",
    tag: "Recognition Day",
  },
  {
    id: 53,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Plantation%20Activity%20(3).png",
    alt: "Plantation Activity",
    title: "Plantation Activity",
    tag: "CSR Day",
  },
  {
    id: 54,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Christmas%20Celebration%20(2).png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 55,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Womans%20Day.png",
    alt: "Womans Day Celebration",
    title: "Womans Day Celebration",
    tag: "Celebration Day",
  },
  {
    id: 56,
    type: "vid",
    thumb: "https://img.youtube.com/vi/aukvIza8e6w/hqdefault.jpg",
    alt: "Forest Day",
    title: "Forest Day",
    tag: "Activity Reel",
    video: "https://www.youtube.com/shorts/aukvIza8e6w",
  },
  {
    id: 57,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Omkareshwar%20Trip%20(7).png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 58,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Team%20Growwstacks%20(5).png",
    alt: "Team GrowwStacks",
    title: "Team GrowwStacks",
    tag: "Spirit Day",
  },
  {
    id: 59,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Diwali%20Celebration%20(2).png",
    alt: "Diwali Celebration",
    title: "Diwali Celebration",
    tag: "Festival Day",
  },
  {
    id: 60,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Mask%20Activity%20(3).png",
    alt: "Mask Activity",
    title: "Mask Activity",
    tag: "Creative Day",
  },
  {
    id: 61,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Campus%20Drive%20(3).png",
    alt: "Campus Drive",
    title: "Campus Drive",
    tag: "Campus Day",
  },
  {
    id: 62,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Turf%20Activity%20(2).png",
    alt: "Turf Activity",
    title: "Turf Activity",
    tag: "Sports Day",
  },
  {
    id: 64,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Welcoming%20New%20Gems%20V2.png",
    alt: "Welcoming New Gems",
    title: "Welcoming New Gems",
    tag: "Welcome Day",
  },
  {
    id: 65,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Laddu%20Activity%20Goushala.png",
    alt: "Laddu Activity Goushala",
    title: "Laddu Activity Goushala",
    tag: "CSR Day",
  },
  {
    id: 66,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Christmas%20Celebration-2.png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 67,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Office%20Visit.png",
    alt: "Office Visit",
    title: "Office Visit",
    tag: "Work Day",
  },
  {
    id: 68,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Make%20Platanium%20Celebration%20(4).png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
  {
    id: 69,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/TRip%20Omkareshwr.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 70,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Womans%20Day%20(2).png",
    alt: "Womans Day Celebration",
    title: "Womans Day Celebration",
    tag: "Celebration Day",
  },
  {
    id: 71,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Placment%20Drive.png",
    alt: "Placement Drive",
    title: "Placement Drive",
    tag: "Campus Day",
  },
  {
    id: 73,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Plantation%20Activity%20(4).png",
    alt: "Plantation Activity",
    title: "Plantation Activity",
    tag: "CSR Day",
  },
  {
    id: 74,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Diwali%20Celebration%20(4).png",
    alt: "Diwali Celebration",
    title: "Diwali Celebration",
    tag: "Festival Day",
  },
  {
    id: 75,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Team%20Growwstacks%20(4).png",
    alt: "Team GrowwStacks",
    title: "Team GrowwStacks",
    tag: "Spirit Day",
  },
  {
    id: 76,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Clay%20Activity%20(4).png",
    alt: "Clay Activity",
    title: "Clay Activity",
    tag: "Creative Day",
  },
  {
    id: 77,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Omlareshwar%20Trip.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 78,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Fun%20Activity%20(2).png",
    alt: "Fun Activity",
    title: "Fun Activity",
    tag: "Fun Day",
  },
  {
    id: 79,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Campus%20Drive%20(5).png",
    alt: "Campus Drive",
    title: "Campus Drive",
    tag: "Campus Day",
  },
  {
    id: 80,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Cristmas%20Celebration%20(3).png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 81,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Make%20Platanium%20Celebration%202.png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
  {
    id: 82,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Laddu%20Activity%20(3).png",
    alt: "Laddu Activity",
    title: "Laddu Activity",
    tag: "Activity Day",
  },
  {
    id: 83,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Office%20Visit%20(4).png",
    alt: "Office Visit",
    title: "Office Visit",
    tag: "Work Day",
  },
  {
    id: 85,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Plantation%20Activity%20(6).png",
    alt: "Plantation Activity",
    title: "Plantation Activity",
    tag: "CSR Day",
  },
  {
    id: 86,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Womans%20Day%20(5).png",
    alt: "Womans Day Celebration",
    title: "Womans Day Celebration",
    tag: "Celebration Day",
  },
  {
    id: 87,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Christmas%20Celebration%20-3.png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 88,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Welcoming%20New%20Gems%20V1%20(2).png",
    alt: "Welcoming New Gems",
    title: "Welcoming New Gems",
    tag: "Welcome Day",
  },
  {
    id: 89,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Make%20Platanium%20Celebration-3.png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
  {
    id: 90,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Omkareshwar%20Trip.png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 92,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Clay%20Activity%20(3).png",
    alt: "Clay Activity",
    title: "Clay Activity",
    tag: "Creative Day",
  },
  {
    id: 93,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Campus%20Drive%20(2).png",
    alt: "Campus Drive",
    title: "Campus Drive",
    tag: "Campus Day",
  },
  {
    id: 94,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Cristmas%20Celebration%20(2).png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 95,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Team%20Growwstacks%20(2).png",
    alt: "Team GrowwStacks",
    title: "Team GrowwStacks",
    tag: "Spirit Day",
  },
  {
    id: 96,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Office%20Visit%20(3).png",
    alt: "Office Visit",
    title: "Office Visit",
    tag: "Work Day",
  },
  {
    id: 97,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Cristmas.png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 98,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Welcoming%20New%20Gems%20V2%20(2).png",
    alt: "Welcoming New Gems",
    title: "Welcoming New Gems",
    tag: "Welcome Day",
  },
  {
    id: 99,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Make%20Platanium%20Celebration%20(5).png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
  {
    id: 100,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Placement%20Drive.png",
    alt: "Placement Drive",
    title: "Placement Drive",
    tag: "Campus Day",
  },
  {
    id: 101,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Womans%20Day%20(3).png",
    alt: "Womans Day Celebration",
    title: "Womans Day Celebration",
    tag: "Celebration Day",
  },
  {
    id: 102,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/RNR%20Celebration%20(3).png",
    alt: "RNR Celebration",
    title: "RNR Celebration",
    tag: "Recognition Day",
  },
  {
    id: 103,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Office%20Visit%20(2).png",
    alt: "Office Visit",
    title: "Office Visit",
    tag: "Work Day",
  },
  {
    id: 104,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Campus%20Drive%20(4).png",
    alt: "Campus Drive",
    title: "Campus Drive",
    tag: "Campus Day",
  },
  {
    id: 105,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Make%20Platanium%20Celebration%20(6).png",
    alt: "Make Platinum Celebration",
    title: "Make Platinum Celebration",
    tag: "Spirit Day",
  },
  {
    id: 106,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Christmas%20Celebration-2%20(2).png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
  {
    id: 107,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Welcoming%20New%20Gems%20V1%20(3).png",
    alt: "Welcoming New Gems",
    title: "Welcoming New Gems",
    tag: "Welcome Day",
  },
  {
    id: 108,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/RNR%20Activity%20(3).png",
    alt: "RNR Activity",
    title: "RNR Activity",
    tag: "Recognition Day",
  },
  {
    id: 109,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Office%20Visit%20(5).png",
    alt: "Office Visit",
    title: "Office Visit",
    tag: "Work Day",
  },
  {
    id: 110,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Omkareshwar%20Trip%20(2).png",
    alt: "Omkareshwar Trip",
    title: "Omkareshwar Trip",
    tag: "Trip Day",
  },
  {
    id: 111,
    type: "img",
    src: "https://ik.imagekit.io/r2zdlyze2o/Office%20/Activity-Growwstacks/gallary/Christmas%20Celebration%20(4).png",
    alt: "Christmas Celebration",
    title: "Christmas Celebration",
    tag: "Festival Day",
  },
];